=== Mysterioun/PortalNF/src/main/resources/nfexml/dtd/nfe.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT nfeProc (NFe, protNFe)>
        <!ATTLIST nfeProc versao CDATA #REQUIRED>
        <!ATTLIST nfeProc xmlns CDATA #REQUIRED>

        <!ELEMENT NFe (infNFe, Signature)>
        <!ATTLIST NFe xmlns CDATA #REQUIRED>

        <!ELEMENT infNFe (ide, emit, dest, det+, total, transp, cobr, pag, infAdic, infRespTec?)>
        <!ATTLIST infNFe versao CDATA #REQUIRED
                Id CDATA #REQUIRED>

        <!ELEMENT ide (cUF, cNF, natOp, mod, serie, nNF, dhEmi, dhSaiEnt, tpNF, idDest, cMunFG, tpImp, tpEmis, cDV, tpAmb, finNFe, indFinal, indPres, indIntermed, procEmi, verProc)>
        <!ELEMENT cUF (#PCDATA)>
        <!ELEMENT cNF (#PCDATA)>
        <!ELEMENT natOp (#PCDATA)>
        <!ELEMENT mod (#PCDATA)>
        <!ELEMENT serie (#PCDATA)>
        <!ELEMENT nNF (#PCDATA)>
        <!ELEMENT dhEmi (#PCDATA)>
        <!ELEMENT dhSaiEnt (#PCDATA)>
        <!ELEMENT tpNF (#PCDATA)>
        <!ELEMENT idDest (#PCDATA)>
        <!ELEMENT cMunFG (#PCDATA)>
        <!ELEMENT tpImp (#PCDATA)>
        <!ELEMENT tpEmis (#PCDATA)>
        <!ELEMENT cDV (#PCDATA)>
        <!ELEMENT tpAmb (#PCDATA)>
        <!ELEMENT finNFe (#PCDATA)>
        <!ELEMENT indFinal (#PCDATA)>
        <!ELEMENT indPres (#PCDATA)>
        <!ELEMENT indIntermed (#PCDATA)>
        <!ELEMENT procEmi (#PCDATA)>
        <!ELEMENT verProc (#PCDATA)>

        <!ELEMENT emit (CNPJ, xNome, xFant, enderEmit, IE, IM, CNAE, CRT)>
        <!ELEMENT CNPJ (#PCDATA)>
        <!ELEMENT xNome (#PCDATA)>
        <!ELEMENT xFant (#PCDATA)>
        <!ELEMENT IE (#PCDATA)>
        <!ELEMENT IM (#PCDATA)>
        <!ELEMENT CNAE (#PCDATA)>
        <!ELEMENT CRT (#PCDATA)>

        <!ELEMENT enderEmit (xLgr, nro, xBairro, cMun, xMun, UF, CEP, cPais, xPais, fone)>
        <!ELEMENT xLgr (#PCDATA)>
        <!ELEMENT nro (#PCDATA)>
        <!ELEMENT xBairro (#PCDATA)>
        <!ELEMENT cMun (#PCDATA)>
        <!ELEMENT xMun (#PCDATA)>
        <!ELEMENT UF (#PCDATA)>
        <!ELEMENT CEP (#PCDATA)>
        <!ELEMENT cPais (#PCDATA)>
        <!ELEMENT xPais (#PCDATA)>
        <!ELEMENT fone (#PCDATA)>

        <!ELEMENT dest (CPF, xNome, enderDest, indIEDest, email)>
        <!ELEMENT CPF (#PCDATA)>
        <!ELEMENT indIEDest (#PCDATA)>
        <!ELEMENT email (#PCDATA)>

        <!ELEMENT enderDest (xLgr, nro, xCpl, xBairro, cMun, xMun, UF, CEP, cPais, xPais, fone)>
        <!ELEMENT xCpl (#PCDATA)>

        <!ELEMENT det (prod, imposto)>
        <!ATTLIST det nItem CDATA #REQUIRED>

        <!ELEMENT prod (cProd, cEAN?, xProd, NCM, cBenef?, CFOP, uCom, qCom, vUnCom, vProd, cEANTrib?, uTrib, qTrib, vUnTrib,vFrete?, indTot, nItemPed?)>
        <!ELEMENT cProd (#PCDATA)>
        <!ELEMENT cEAN (#PCDATA)>
        <!ELEMENT xProd (#PCDATA)>
        <!ELEMENT NCM (#PCDATA)>
        <!ELEMENT cBenef (#PCDATA)>
        <!ELEMENT CFOP (#PCDATA)>
        <!ELEMENT uCom (#PCDATA)>
        <!ELEMENT qCom (#PCDATA)>
        <!ELEMENT vUnCom (#PCDATA)>
        <!ELEMENT cEANTrib (#PCDATA)>
        <!ELEMENT uTrib (#PCDATA)>
        <!ELEMENT qTrib (#PCDATA)>
        <!ELEMENT vUnTrib (#PCDATA)>
        <!ELEMENT indTot (#PCDATA)>
        <!ELEMENT nItemPed (#PCDATA)>

        <!ELEMENT imposto (vTotTrib, ICMS,IPI?, PIS, COFINS, ICMSUFDest)>
        <!ELEMENT IPI (cEnq, IPITrib)>
        <!ELEMENT cEnq (#PCDATA)>

        <!ELEMENT IPITrib (CST, vBC, pIPI, vIPI)>
        <!ELEMENT pIPI (#PCDATA)>


        <!ELEMENT ICMS (ICMS00)>
        <!ELEMENT ICMS00 (orig, CST, modBC, vBC, pICMS, vICMS)>
        <!ELEMENT orig (#PCDATA)>
        <!ELEMENT CST (#PCDATA)>
        <!ELEMENT modBC (#PCDATA)>
        <!ELEMENT vBC (#PCDATA)>
        <!ELEMENT pICMS (#PCDATA)>
        <!ELEMENT PIS (PISAliq)>
        <!ELEMENT PISAliq (CST, vBC, pPIS, vPIS)>
        <!ELEMENT pPIS (#PCDATA)>
        <!ELEMENT COFINS (COFINSAliq)>
        <!ELEMENT COFINSAliq (CST, vBC, pCOFINS, vCOFINS)>
        <!ELEMENT pCOFINS (#PCDATA)>
        <!ELEMENT ICMSUFDest (vBCUFDest, vBCFCPUFDest, pFCPUFDest, pICMSUFDest, pICMSInter, pICMSInterPart, vFCPUFDest, vICMSUFDest, vICMSUFRemet)>
        <!ELEMENT vBCUFDest (#PCDATA)>
        <!ELEMENT vBCFCPUFDest (#PCDATA)>
        <!ELEMENT pFCPUFDest (#PCDATA)>
        <!ELEMENT pICMSUFDest (#PCDATA)>
        <!ELEMENT pICMSInter (#PCDATA)>
        <!ELEMENT pICMSInterPart (#PCDATA)>
        <!ELEMENT vFCPUFDest (#PCDATA)>
        <!ELEMENT vICMSUFDest (#PCDATA)>
        <!ELEMENT vICMSUFRemet (#PCDATA)>

        <!ELEMENT total (ICMSTot)>
        <!ELEMENT ICMSTot (vBC, vICMS, vICMSDeson,vICMSUFDest?, vFCP, vBCST, vST, vFCPST, vFCPSTRet, vProd, vFrete?, vSeg, vDesc, vII, vIPI, vIPIDevol, vPIS, vCOFINS, vOutro, vNF, vTotTrib)>
        <!ELEMENT vICMS (#PCDATA)>
        <!ELEMENT vICMSDeson (#PCDATA)>
        <!ELEMENT vFCP (#PCDATA)>
        <!ELEMENT vBCST (#PCDATA)>
        <!ELEMENT vST (#PCDATA)>
        <!ELEMENT vFCPST (#PCDATA)>
        <!ELEMENT vFCPSTRet (#PCDATA)>
        <!ELEMENT vProd (#PCDATA)>
        <!ELEMENT vFrete (#PCDATA)>
        <!ELEMENT vSeg (#PCDATA)>
        <!ELEMENT vII (#PCDATA)>
        <!ELEMENT vIPI (#PCDATA)>
        <!ELEMENT vIPIDevol (#PCDATA)>
        <!ELEMENT vPIS (#PCDATA)>
        <!ELEMENT vCOFINS (#PCDATA)>
        <!ELEMENT vOutro (#PCDATA)>
        <!ELEMENT vNF (#PCDATA)>
        <!ELEMENT vTotTrib (#PCDATA)>

        <!ELEMENT transp (modFrete, transporta, vol)>
        <!ELEMENT modFrete (#PCDATA)>
        <!ELEMENT transporta (CNPJ?, xNome,IE?, xEnder?, xMun?, UF?)>
        <!ELEMENT xEnder (#PCDATA)>


        <!ELEMENT vol (qVol, esp, pesoL, pesoB)>
        <!ELEMENT qVol (#PCDATA)>
        <!ELEMENT esp (#PCDATA)>
        <!ELEMENT pesoL (#PCDATA)>
        <!ELEMENT pesoB (#PCDATA)>

        <!ELEMENT cobr (fat, dup)>
        <!ELEMENT fat (nFat, vOrig, vDesc, vLiq)>
        <!ELEMENT nFat (#PCDATA)>
        <!ELEMENT vOrig (#PCDATA)>
        <!ELEMENT vDesc (#PCDATA)>
        <!ELEMENT vLiq (#PCDATA)>
        <!ELEMENT dup (nDup, dVenc, vDup)>
        <!ELEMENT nDup (#PCDATA)>
        <!ELEMENT dVenc (#PCDATA)>
        <!ELEMENT vDup (#PCDATA)>

        <!ELEMENT pag (detPag)>
        <!ELEMENT detPag (tPag, vPag)>
        <!ELEMENT tPag (#PCDATA)>
        <!ELEMENT vPag (#PCDATA)>

        <!ELEMENT infAdic (infCpl)>
        <!ELEMENT infCpl (#PCDATA)>

        <!ELEMENT infRespTec (CNPJ, xContato, email, fone)>
        <!ELEMENT xContato (#PCDATA)>

        <!ELEMENT Signature (SignedInfo, SignatureValue, KeyInfo)>
        <!ATTLIST Signature xmlns CDATA #REQUIRED>

        <!ELEMENT SignedInfo (CanonicalizationMethod, SignatureMethod, Reference)>
        <!ELEMENT CanonicalizationMethod (#PCDATA)>
        <!ATTLIST CanonicalizationMethod Algorithm CDATA #REQUIRED>

        <!ELEMENT SignatureMethod (#PCDATA)>
        <!ATTLIST SignatureMethod Algorithm CDATA #REQUIRED>

        <!ELEMENT Reference (Transforms, DigestMethod,DigestValue)>
        <!ATTLIST Reference URI CDATA #REQUIRED>

        <!ELEMENT DigestMethod (#PCDATA)>
        <!ATTLIST DigestMethod Algorithm CDATA #REQUIRED>
        <!ELEMENT DigestValue (#PCDATA)>


        <!ELEMENT Transforms (Transform+)>
        <!ELEMENT Transform (#PCDATA)>
        <!ATTLIST Transform Algorithm CDATA #REQUIRED>

        <!ELEMENT SignatureValue (#PCDATA)>
        <!ELEMENT KeyInfo (X509Data)>
        <!ELEMENT X509Data (X509Certificate)>
        <!ELEMENT X509Certificate (#PCDATA)>


        <!ELEMENT protNFe (infProt)>
        <!ATTLIST protNFe versao CDATA #REQUIRED>

        <!ELEMENT infProt (tpAmb, verAplic, chNFe, dhRecbto, nProt, digVal, cStat, xMotivo)>
        <!ELEMENT verAplic (#PCDATA)>
        <!ELEMENT chNFe (#PCDATA)>
        <!ELEMENT dhRecbto (#PCDATA)>
        <!ELEMENT nProt (#PCDATA)>
        <!ELEMENT digVal (#PCDATA)>
        <!ELEMENT cStat (#PCDATA)>
        <!ELEMENT xMotivo (#PCDATA)>


        <!ELEMENT CSOSN (#PCDATA)>

=== Mysterioun/PortalNF/src/main/resources/nfexml/nfe2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nfeProc SYSTEM "dtd/nfe.dtd">
<nfeProc xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
    <NFe xmlns="http://www.portalfiscal.inf.br/nfe">
        <infNFe versao="4.00" Id="NFe42211107993973000380550010009751421562620964">
            <ide>
                <cUF>42</cUF>
                <cNF>56262096</cNF>
                <natOp>Venda de mercadorias</natOp>
                <mod>55</mod>
                <serie>1</serie>
                <nNF>975142</nNF>
                <dhEmi>2021-11-16T14:07:34-03:00</dhEmi>
                <dhSaiEnt>2021-11-16T14:07:34-03:00</dhSaiEnt>
                <tpNF>1</tpNF>
                <idDest>2</idDest>
                <cMunFG>4209102</cMunFG>
                <tpImp>1</tpImp>
                <tpEmis>1</tpEmis>
                <cDV>4</cDV>
                <tpAmb>1</tpAmb>
                <finNFe>1</finNFe>
                <indFinal>1</indFinal>
                <indPres>2</indPres>
                <indIntermed>0</indIntermed>
                <procEmi>0</procEmi>
                <verProc>Bling 1.0</verProc>
            </ide>
            <emit>
                <CNPJ>07993973000380</CNPJ>
                <xNome>TERABYTE ATACADO E VAREJO DE PRODUTOS DE INFORMATICA LTDA</xNome>
                <xFant>TERABYTESHOP</xFant>
                <enderEmit>
                    <xLgr>Rua Ottokar Doerffel</xLgr>
                    <nro>1112</nro>
                    <xBairro>Atiradores</xBairro>
                    <cMun>4209102</cMun>
                    <xMun>Joinville</xMun>
                    <UF>SC</UF>
                    <CEP>89203212</CEP>
                    <cPais>1058</cPais>
                    <xPais>Brasil</xPais>
                    <fone>4130862957</fone>
                </enderEmit>
                <IE>257944265</IE>
                <IM>208486</IM>
                <CNAE>4751201</CNAE>
                <CRT>3</CRT>
            </emit>
            <dest>
                <CPF>11111111111</CPF>
                <xNome>CHRISTIAN ALVES</xNome>
                <enderDest>
                    <xLgr>Rua Padre Julio Sachet</xLgr>
                    <nro>67</nro>
                    <xCpl>Casa</xCpl>
                    <xBairro>Nossa Senhora do Perpetuo Socorro</xBairro>
                    <cMun>4316907</cMun>
                    <xMun>Santa Maria</xMun>
                    <UF>RS</UF>
                    <CEP>97045380</CEP>
                    <cPais>1058</cPais>
                    <xPais>Brasil</xPais>
                    <fone>5599999999</fone>
                </enderDest>
                <indIEDest>9</indIEDest>
                <email>christian@gmail.com</email>
            </dest>
            <det nItem="1">
                <prod>
                    <cProd>4715109922516</cProd>
                    <cEAN>SEM GTIN</cEAN>
                    <xProd>Kit Fan com 2 Unidades Raijintek SKLERA 12 RBW ADD-2, ARGB, 120mm, 0R40B00129</xProd>
                    <NCM>84145990</NCM>
                    <CFOP>6108</CFOP>
                    <uCom>un</uCom>
                    <qCom>1.0000</qCom>
                    <vUnCom>49.99</vUnCom>
                    <vProd>49.99</vProd>
                    <cEANTrib>SEM GTIN</cEANTrib>
                    <uTrib>un</uTrib>
                    <qTrib>1.0000</qTrib>
                    <vUnTrib>49.99</vUnTrib>
                    <indTot>1</indTot>
                    <nItemPed>1</nItemPed>
                </prod>
                <imposto>
                    <vTotTrib>9.52</vTotTrib>
                    <ICMS>
                        <ICMS00>
                            <orig>0</orig>
                            <CST>00</CST>
                            <modBC>3</modBC>
                            <vBC>49.99</vBC>
                            <pICMS>12.0000</pICMS>
                            <vICMS>6.00</vICMS>
                        </ICMS00>
                    </ICMS>
                    <PIS>
                        <PISAliq>
                            <CST>01</CST>
                            <vBC>43.99</vBC>
                            <pPIS>1.65</pPIS>
                            <vPIS>0.73</vPIS>
                        </PISAliq>
                    </PIS>
                    <COFINS>
                        <COFINSAliq>
                            <CST>01</CST>
                            <vBC>43.99</vBC>
                            <pCOFINS>7.60</pCOFINS>
                            <vCOFINS>3.34</vCOFINS>
                        </COFINSAliq>
                    </COFINS>
                    <ICMSUFDest>
                        <vBCUFDest>49.99</vBCUFDest>
                        <vBCFCPUFDest>49.99</vBCFCPUFDest>
                        <pFCPUFDest>0.0000</pFCPUFDest>
                        <pICMSUFDest>13.5000</pICMSUFDest>
                        <pICMSInter>12.00</pICMSInter>
                        <pICMSInterPart>100.0000</pICMSInterPart>
                        <vFCPUFDest>0.00</vFCPUFDest>
                        <vICMSUFDest>0.75</vICMSUFDest>
                        <vICMSUFRemet>0.00</vICMSUFRemet>
                    </ICMSUFDest>
                </imposto>
            </det>
            <total>
                <ICMSTot>
                    <vBC>49.99</vBC>
                    <vICMS>6.00</vICMS>
                    <vICMSDeson>0.00</vICMSDeson>
                    <vICMSUFDest>0.75</vICMSUFDest>
                    <vFCP>0.00</vFCP>
                    <vBCST>0.00</vBCST>
                    <vST>0.00</vST>
                    <vFCPST>0.00</vFCPST>
                    <vFCPSTRet>0.00</vFCPSTRet>
                    <vProd>49.99</vProd>
                    <vFrete>0.00</vFrete>
                    <vSeg>0.00</vSeg>
                    <vDesc>0.00</vDesc>
                    <vII>0.00</vII>
                    <vIPI>0.00</vIPI>
                    <vIPIDevol>0.00</vIPIDevol>
                    <vPIS>0.73</vPIS>
                    <vCOFINS>3.34</vCOFINS>
                    <vOutro>0.00</vOutro>
                    <vNF>49.99</vNF>
                    <vTotTrib>9.52</vTotTrib>
                </ICMSTot>
            </total>
            <transp>
                <modFrete>0</modFrete>
                <transporta>
                    <xNome>Jad Logistica Ltda.</xNome>
                </transporta>
                <vol>
                    <qVol>1</qVol>
                    <esp>Volumes</esp>
                    <pesoL>0.000</pesoL>
                    <pesoB>1.000</pesoB>
                </vol>
            </transp>
            <cobr>
                <fat>
                    <nFat>975142</nFat>
                    <vOrig>49.99</vOrig>
                    <vDesc>0</vDesc>
                    <vLiq>49.99</vLiq>
                </fat>
                <dup>
                    <nDup>001</nDup>
                    <dVenc>2021-11-17</dVenc>
                    <vDup>49.99</vDup>
                </dup>
            </cobr>
            <pag>
                <detPag>
                    <tPag>01</tPag>
                    <vPag>49.99</vPag>
                </detPag>
            </pag>
            <infAdic>
                <infCpl>Total aproximado de tributos: R$ 9,52 (19,04%) Federais R$ 6,72 (13,45%) Estaduais R$ 2,80 (5,60%) . Fonte IBPT.&lt;br /&gt;Base Legal da reducao de ICMS Artigo 23, inciso XVI, alinea "b", do Livro I do RICMS/RS. ***Suspendida a exigibilidade da cobranca dos creditos tributarios relativos ao DIFAL e ao adicional para o FECP em detrimento de decisao judicial exarada nos Autos n 5020303-53.2021.8.21.0001 da 6 Vara da Fazenda Publica de Porto Alegre/RS.&lt;br /&gt;Valor do ICMS DIFAL para UF de destino R$ 0,75&lt;br /&gt;Pedido: 3716335</infCpl>
            </infAdic>
            <infRespTec>
                <CNPJ>01056417000139</CNPJ>
                <xContato>Organisys Software SA</xContato>
                <email>fiscal@bling.com.br</email>
                <fone>05430579470</fone>
            </infRespTec>
        </infNFe>
        <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
                <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
                <Reference URI="#NFe42211107993973000380550010009751421562620964">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                    <DigestValue>KAC5oCIV3OO/WTh7lUDvE0+E3Gg=</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>
                paDnxOxSHKqqLopmVIKpSoPpIRmYoiHfJg5DlaPBwOVyDn+CHB+y2LFBD2oa/WImsHdRRkqAojujTmPxvwicfKVMP0AVlkJfWjJKTnY5NtmCYLBM2Aydw+mxjiz11iLBljKj91CQ9gZ3TyIRG1c8SqU6EQpzNzvKEAqEyZ4qoHX2PNKIy8f9YzMLYVAVvVALj8lJb4agQbqJ279wAt5DtKV7uz+6hGNQ6ATUoeDjpjmU3SC6m3j1HXdOX21cMBqDrg91tCZShai+z5+JQFYDE4/wGcFtBuy5UTHNbLPF7+P2FrlMtUYJG28x30lyFZNZa4t5nnzIAuEbSgXA3+HfOQ==</SignatureValue>
            <KeyInfo>
                <X509Data>
                    <X509Certificate>
